id: PFAF48617
initial_creation_type: ocr
source_metadata:
  volumes:
    989b3f74ad9244cdb0be0cfdb5b0973c:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: གཙུག་ཏོར་དྲི་མ་མེད་པར་སྣང་བའི་གཟུངས་བཀླག་ཅིང་མཆོད་རྟེན་བརྒྱ་རྩ་བརྒྱད་དམ་མཆོད་རྟེན་ལྔ་གདབ་པའི་ཆོ་ག་མདོ་སད་ལས་བསྡུས་པ།
      total_pages: 1044
      volume_number: 38
